# Generated by Django 4.1 on 2022-10-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convenioweb',
            old_name='name',
            new_name='no_convenio',
        ),
        migrations.RenameField(
            model_name='historicalconvenioweb',
            old_name='name',
            new_name='no_convenio',
        ),
    ]
