# Generated by Django 4.1 on 2022-08-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_resetpwd',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_resetpwd',
            field=models.BooleanField(default=True),
        ),
    ]
