# Generated by Django 4.1 on 2022-08-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_historicaluser_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
