# Generated by Django 4.1 on 2022-09-07 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_historicaluser_image_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='id_erp',
            field=models.CharField(default='sadjkashdaskjdhaskjdhaskd', max_length=255, verbose_name='id-ERP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_erp',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='id-ERP'),
            preserve_default=False,
        ),
    ]
