# Generated by Django 4.1 on 2022-09-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historicaluser_id_erp_user_id_erp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='is_staff',
            new_name='is_distribuidor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_distribuidor',
        ),
    ]
