# Generated by Django 4.1 on 2022-10-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_historicaluser_is_distribuidor_user_is_distribuidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido'),
        ),
    ]
