# Generated by Django 4.1 on 2022-11-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_historicaluser_last_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(db_index=True, default='admin', max_length=255, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=255, unique=True, verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
